// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17GrHQ3HHPdmC-zgGDAZovHBBdp_QoGQ',
    appId: '1:855668906906:web:cb73ab26187c9caaf37823',
    messagingSenderId: '855668906906',
    projectId: 'movies-app-48256',
    authDomain: 'movies-app-48256.firebaseapp.com',
    storageBucket: 'movies-app-48256.appspot.com',
    measurementId: 'G-0D2YN5W7MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JLW3z9oX_vsR_oaWdg_hzzGKzIZpGek',
    appId: '1:855668906906:android:3bc48caaefea12a1f37823',
    messagingSenderId: '855668906906',
    projectId: 'movies-app-48256',
    storageBucket: 'movies-app-48256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncm0xLXX6xcjSQlVYOroYvVa_xJkuFX0',
    appId: '1:855668906906:ios:f59d0110344bdb60f37823',
    messagingSenderId: '855668906906',
    projectId: 'movies-app-48256',
    storageBucket: 'movies-app-48256.appspot.com',
    iosClientId: '855668906906-kj0vemtrbmfj0n9rotthsa87dtd0ecd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
